---
abstract: 'Language-based charset reference'
author:
  - 'John Wang <jwang@cpan.org>'
build_requires:
  JSON::Any: 0
  Test::Simple: 0
  strict: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.130880'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-Charsets
requires:
  Moose: 0
  MooseX::StrictConstructor: 0
  namespace::autoclean: 0
version: 0.04
